## Data Science Bootcamp

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 221](#1)
* [Ćwiczenie 222](#2)
* [Ćwiczenie 223](#3)
* [Ćwiczenie 224](#4)
* [Ćwiczenie 225](#5)
* [Ćwiczenie 226](#6)
* [Ćwiczenie 227](#7)
* [Ćwiczenie 228](#8)
* [Ćwiczenie 229](#9)
* [Ćwiczenie 230](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
np.random.seed(20)

np.__version__

'1.21.6'

### <a name='a11'></a> Rozwiązywanie układów równań
Rozważmy układ równań $U$:  
$${\displaystyle \mathrm {U} \colon {\begin{cases}{\begin{matrix}a_{11}x_{1}&+&a_{12}x_{2}&+&\dots &+&a_{1n}x_{n}&=b_{1},\\a_{21}x_{1}&+&a_{22}x_{2}&+&\dots &+&a_{2n}x_{n}&=b_{2},\\\vdots &&\vdots &&\ddots &&\vdots &\vdots \\a_{m1}x_{1}&+&a_{m2}x_{2}&+&\dots &+&a_{mn}x_{n}&=b_{m}.\end{matrix}}\end{cases}}.}$$

Wykorzystując macierze możemy to przedstawić następująco:

$${\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}{\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$
I w zapisie skrótowym:
$$\mathbf {AX} =\mathbf {B}$$

Gdzie:  
$A = {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}$ - macierz współczynników

${\displaystyle \mathbf {B} =[b_{1},b_{2},\dots ,b_{m}]} $ - wektor wyrazów wolnych  
${\mathbf  X}=[x_{1},x_{2},\dots ,x_{n}] $ - wektor niewiadomych

Jeśli macierz układu $A$ jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.
$$\mathbf {AX} =\mathbf {B}$$
$${\displaystyle \mathbf {A} ^{-1}\mathbf {AX} =\mathbf {A} ^{-1}\mathbf {B}} $$
$$\mathbf {X} =\mathbf {A} ^{-1}\mathbf {B} .$$

#### Przykład:
Rozważmy układ równań:
$$\begin{cases}2x + 4y = 10 \\ x - y = -1 \end{cases}$$  
Rozwiązaniem jest para liczb:
$$\begin{cases}x = 1 \\ y = 2 \end{cases}$$  


### <a name='1'></a> Ćwiczenie 221
Wykorzystując bibliotekę numpy rozwiąż poniższy układ równań:

$$\begin{cases}5x - 3y = 21 \\ x - 2y = 7 \end{cases}$$

In [2]:
A = np.array([[5, -3], [1, -2]])
B = np.array([[21], [7]])
print(A)
print(B)

[[ 5 -3]
 [ 1 -2]]
[[21]
 [ 7]]


In [3]:
X = np.dot(np.linalg.inv(A), B)
X

array([[ 3.],
       [-2.]])

In [4]:
X = np.linalg.solve(A, B)
X

array([[ 3.],
       [-2.]])

Dokonaj sprawdzenia. 

__Wskazówka:__ Użyj funkcji _np.allclose()_.

In [5]:
np.allclose(np.dot(A, X), B)

True

### <a name='2'></a> Ćwiczenie 222
Wykorzystując bibliotekę numpy rozwiąż poniższy układ równań:

$$\begin{cases}x + y + z = 1 \\ 2x + y + 5z = 0 \\ x - y = z \end{cases}$$

In [6]:
A = np.array([[1, 1, 1], [2, 1, 5], [1, -1, -1]])
B = np.array([[1], [0], [0]])
print(A)
print(B)

[[ 1  1  1]
 [ 2  1  5]
 [ 1 -1 -1]]
[[1]
 [0]
 [0]]


In [7]:
X = np.dot(np.linalg.inv(A), B)
X

array([[ 0.5  ],
       [ 0.875],
       [-0.375]])

In [8]:
X = np.linalg.solve(A, B)
X

array([[ 0.5  ],
       [ 0.875],
       [-0.375]])

Dokonaj sprawdzenia. 

__Wskazówka:__ Użyj funkcji _np.allclose()_.

In [9]:
np.allclose(np.dot(A, X), B)

True

### <a name='3'></a> Ćwiczenie 223
Załaduj popularny zbiór danych IRIS do zmiennej _data_raw_ wykorzystując bibliotekę _scikit-learn_.

In [10]:
from sklearn.datasets import load_iris

data_raw = load_iris()
data_raw

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Wyświetl opis zbioru IRIS

In [11]:
print(data_raw['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

Wyświetl nazwy zmiennych w zbiorze.

In [12]:
data_raw['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Wyświetl nazwy klas w zbiorze.

In [13]:
data_raw['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### <a name='4'></a> Ćwiczenie 224
Do zmiennej _data_ przypisz dane (tablica numpy) zbioru IRIS. 

In [14]:
data = data_raw['data']

Do zmiennej _target_ przypisz wartości zmiennej docelowej ze zbioru IRIS.

In [15]:
target = data_raw['target']

Zbadaj kształt zmiennej _data_ oraz _target_.

In [16]:
print(data.shape)
print(target.shape)

(150, 4)
(150,)


### <a name='5'></a> Ćwiczenie 225
Podziel dane na zbiór treningowy (_data_train_, _target_train_) i testowy (_data_test_, _target_test_). Rozmiar zbioru testowego to 30% próbek.

In [17]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3)

Wyświetl rozmiar zbiorów:
* _data_train_
* _target_train_
* _data_test_
* _target_test_

In [18]:
print(f'data_train shape: {data_train.shape}')
print(f'target_train shape: {target_train.shape}')
print(f'data_test shape: {data_test.shape}')
print(f'target_test shape: {target_test.shape}')

data_train shape: (105, 4)
target_train shape: (105,)
data_test shape: (45, 4)
target_test shape: (45,)


### <a name='6'></a> Ćwiczenie 226 
Zbuduj model regresji logistcznej (ustaw domyślne wartości parametrów) wykorzystując bibliotekę scikit-learn oraz dane IRIS.

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

Dopasuj dane treningowe do modelu.

In [20]:
model.fit(data_train, target_train)

LogisticRegression()

### <a name='7'></a> Ćwiczenie 227
Dokonaj oceny modelu na zbiorze treningowym.

In [21]:
model.score(data_train, target_train)

0.9714285714285714

Dokonaj oceny modelu na zbiorze testowym.

In [22]:
model.score(data_test, target_test)

0.9333333333333333

### <a name='8'></a> Ćwiczenie 228
Dokonaj predykcji na danych testowych na podstawie modelu i przypisz je do zmiennej _target\_pred_.

In [23]:
target_pred = model.predict(data_test)

Wyświetl zmienną _target\_pred_.

In [24]:
target_pred

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 1, 1, 1, 0, 2, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 1,
       1])

Wyświetl zmienną _target\_test_.

In [25]:
target_test

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 1, 1, 1, 0, 2, 2, 1, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2, 0, 1,
       1])

### <a name='9'></a> Ćwiczenie 229
Wyznacz macierz pomyłek (macierz konfuzji) 

In [26]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(target_test, target_pred)
cm

array([[13,  0,  0],
       [ 0, 18,  0],
       [ 0,  3, 11]])

### <a name='10'></a> Ćwiczenie 230
Wyświetl raport klasyfikacji modelu.

In [27]:
from sklearn.metrics import classification_report

print(classification_report(target_test, target_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.86      1.00      0.92        18
           2       1.00      0.79      0.88        14

    accuracy                           0.93        45
   macro avg       0.95      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45

