## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 11](#1)
* [Ćwiczenie 12](#2)
* [Ćwiczenie 13](#3)
* [Ćwiczenie 14](#4)
* [Ćwiczenie 15](#5)
* [Ćwiczenie 16](#6)
* [Ćwiczenie 17](#7)
* [Ćwiczenie 18](#8)
* [Ćwiczenie 19](#9)
* [Ćwiczenie 20](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 11
Zbuduj jednowymiarową tablicę numpy liczb dwucyfrowych.

__Oczekiwany wynik:__


```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```



__Wskazówka:__ Użyj funkcji _np.arange()_.


In [2]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### <a name='2'></a> Ćwiczenie 12
Zbuduj tablicę numpy określoną poniżej:


```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

Zwróć uwagę, że kształt tablicy to (9, 10).


__Wskazówka:__ Użyj funkcji _np.arange()_ oraz metodę _np.ndarray.reshape()_.

In [6]:
np.arange(10,100).reshape(9,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
np.arange(10,100).reshape(-1,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
np.arange(10,100).reshape(9,-1)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Przypomnienie

###  Macierz jednostkowa:

Macierz jednostkowa - macierz kwadratowa, której współczynniki podane są wzorem:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Przykłady
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

### <a name='3'></a> Ćwiczenie 13
Zbuduj tablicę dwuwymiarową (macierz jednostkową) o kształcie _6x6_ mającą na przekątnej jedynki oraz poza same zera. Użyj typu danych _int_.
__Oczekiwany wynik:__


```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```



__Wskazówka:__ Użyj funkcji _np.eye()_.

In [7]:
np.eye(6,dtype="int")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### <a name='4'></a> Ćwiczenie 14
Ustaw ziarno losowe na wartość 10. Następnie zbuduj jednowymiarową tablicę składającą się z 30 pseudolosowo wygenerowanych wartości z rozkładu jednostajnego nad przedziałem $[0, 1)$.

__Oczekiwany wynik:__


```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```



__Wskazówka:__ Użyj funkcji _np.random.rand()_.

In [18]:
import random
random.seed(10)
np.random.rand(30)

array([0.54788967, 0.04303229, 0.18811662, 0.77826869, 0.73386842,
       0.42944769, 0.00991577, 0.00449739, 0.88057118, 0.42662748,
       0.22529189, 0.14893544, 0.78577285, 0.47471669, 0.48511769,
       0.37562992, 0.67113021, 0.30563667, 0.27423364, 0.50316238,
       0.61586299, 0.26934698, 0.55335046, 0.69263063, 0.10374639,
       0.02595272, 0.35769728, 0.21450677, 0.83692916, 0.41173627])

### <a name='5'></a> Ćwiczenie 15
Ustaw ziarno losowe na wartość 20. Następnie zbuduj dwuwymiarową tablicę o kształcie _(10, 4)_ wartości pseudolosowo wygenerowanych ze standardowego rozkładu normalego $N(0, 1)$.

__Oczekiwany wynik:__


```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```



__Wskazówka:__ Użyj funkcji _np.random.randn()_.

In [19]:
random.seed(20)
np.random.randn(40).reshape(10,4)

array([[-0.13559906,  0.43496512,  0.32778191, -0.2061512 ],
       [-0.59778737, -0.10939945,  0.04989919, -0.32989122],
       [ 1.08020683, -0.46226085,  0.32624696, -0.372491  ],
       [ 1.13998831,  1.35424613, -0.00359452,  0.16938753],
       [-1.26084706, -0.08530842,  0.12075442,  1.48573152],
       [-1.10670243,  0.92300854,  0.75492295, -1.54419004],
       [ 0.62708037, -0.14844505, -0.86324861, -0.31427678],
       [ 0.85271438, -0.31353958,  0.15562737,  1.0804016 ],
       [-1.25189786,  0.10074649, -0.11093072, -0.96714739],
       [-0.01600236, -0.97886521, -0.05014656,  0.51592927]])

In [26]:
random.seed(20)
np.random.randn(10,4)

array([[-1.11321176,  0.6255434 , -1.53775731,  1.08774467],
       [-0.51058082, -1.30164248,  0.25732395, -0.76088582],
       [-1.05976637, -0.4198657 ,  1.55920986,  0.50243294],
       [-0.99030778,  0.75732308, -0.68572715, -0.75285069],
       [-0.63729821, -1.3539958 ,  0.80133123,  1.8623647 ],
       [-0.20480071,  1.18573738, -0.21016007, -0.63225761],
       [ 0.57026056, -0.44853186, -1.28373169, -0.20715631],
       [ 1.65931679, -0.60402988,  0.73277663,  0.43244476],
       [ 2.30573541,  0.19578213,  0.68836106,  1.52094069],
       [ 0.05670999, -0.16015355,  1.0493519 ,  0.00825901]])

### <a name='6'></a> Ćwiczenie 16
Ustaw ziarno losowe na wartość 30. Następnie zbuduj dwuwymiarową tablicę o kształcie _(10, 4)_ wartości pseudolosowo wygenerowanych z rozkładu normalego $N(100, 5)$.  
$\mu=100$   
$\sigma^{2}=5$

__Oczekiwany wynik:__


```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```



__Wskazówka:__ Użyj funkcji _np.random.randn()_.

In [27]:
random.seed(30)
100 + np.sqrt(5) * np.random.randn(10, 4)

array([[100.50121241, 103.90251383,  99.06168655, 100.77309916],
       [100.11155006, 101.43282885, 100.13298628,  97.39392462],
       [ 97.19225765,  97.73235362, 100.92987501,  97.07182211],
       [101.13186722,  99.73092904, 100.18703495, 101.86433734],
       [ 99.05035533,  98.93872075,  96.23414935, 100.25891144],
       [ 98.34601275, 100.24378964,  99.66716643,  95.47340865],
       [102.1502459 ,  98.49164511,  99.73920752, 100.11259959],
       [ 99.51343278,  97.63207986, 100.11703062,  99.6548048 ],
       [ 99.75586496, 104.6135344 ,  96.38719058,  97.57182214],
       [102.60615942, 100.55260383, 100.06912128, 102.11175359]])

### <a name='7'></a> Ćwiczenie 17
Iterując po tablicy numpy $A$ element po elemencie (element-wise) wydrukuj każdy element tablicy do konsoli.


```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```



__Wskazówka:__ Użyj funkcji _np.nditer()_.

In [15]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])
for cell in np.nditer(A):
    print(cell, end=' ')

1 4 3 5 2 6 

### <a name='8'></a> Ćwiczenie 18
Utwórz jednowymiarową tablicę numpy (wektor) składający się z 11 równo rozmieszczonych punktów z przedziału $[0, 1].$

__Oczekiwany wynik:__


```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```
__Wskazówka:__ Użyj funkcji _np.linspace()_.


In [16]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### <a name='9'></a> Ćwiczenie 19
Ustaw ziarno losowe na wartość 42. Wygeneruj tablicę jednowymiarową (wektor) zawierający możliwy wynik losowania w grę Duży Lotek. 

__Oczekiwany wynik:__


```
array([39, 29, 15, 43,  8, 21])
```



__Wskazówka:__ Wynikiem losowania jest 6-elementowy wektor wartości od 1 do 49 włącznie.

In [22]:
random.seed(42)
np.linspace(1,49,6, dtype='int')

array([ 1, 10, 20, 29, 39, 49])

### <a name='10'></a> Ćwiczenie 20
Zbuduj dwuwymiarową tablicę numpy rozmiaru _6x6_ podaną poniżej:


```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```
__Wskazówka:__ Użyj funkcji _np.diag()_.


In [23]:
np.diag([0,1,2,3,4,5])

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [28]:
np.diag(np.arange(6))

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])